# Site settings
title: rocknrollers international
header-img: img/home-bg.jpg
email: joshanderson@rti.org
description: "informal show and tell time"
baseurl: ""
url: "http://rocknrollers.international"
twitter_username: rocknrockers
github_username:  rocknrollers

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 20
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
